# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - plazavea-api-cloud

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read 

    steps:
      # CRÍTICO: 1. Checkout solo de la subcarpeta /backend
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          path: backend  # <--- Descarga solo el contenido de 'backend'
          
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # CRÍTICO: 2. Instalar y compilar DENTRO de la subcarpeta
      - name: npm install and build
        run: |
          cd backend  # <--- Entrar a la carpeta para instalar el package.json
          npm install
          npm run build --if-present
          
      # 3. Empaquetar solo el resultado compilado (que está en backend/dist)
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./backend/dist # <--- El artifact apunta a la carpeta compilada

          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write 
      contents: read 

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          # Usar los secretos generados por Azure (no editar los nombres)
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_37AB75CCB8A94CCFAF8B1F4E95C7B252 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E3C6A467B459485B48A819435C719EEA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BF1BA466F7184C70A940C1C858BF4E17 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'plazavea-api-cloud'
          slot-name: 'Production'
          package: . # El paquete es el artifact descargado
          startup-command: 'npm start' # Fuerza a usar el script de arranque 'node dist/app.js'
